version: '3'

volumes:
  murmur:

services:
  teqbot:
    build: .
    image: teqbot
    container_name: teqbot
    depends_on:
      - murmur
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - 8000:8000
    command: /start
    restart: always

  murmur:
    image: goofball222/murmur
    container_name: murmur
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - murmur:/opt/murmur
    environment:
      - TZ=UTC

  redis:
    image: redis:5.0
    container_name: teqbot_redis
