version: '3'

services:
  teqbot:
    build:
      context: .
      dockerfile: compose/production/Dockerfile
    image: teqbot
    container_name: teqbot
    depends_on:
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    command: /start
    restart: always

  murmur:
    image: goofball222/murmur:1.3.3
    container_name: murmur
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./murmur/cert:/opt/murmur/cert
      - ./murmur/config:/opt/murmur/config
      - ./murmur/data:/opt/murmur/data
      - ./murmur/log:/opt/murmur/log
    environment:
      - TZ=UTC

  redis:
    image: redis:5.0
    container_name: teqbot_redis
